Algoritmo "exercicio1"

Var
nome: caractere;
idade: real;


Inicio
      escreval("Digite o seu nome: ")
      leia(nome)
      escreval("Digite a sua idade: ")
      leia(idade)
      escreval("Idade > 18: ", (idade > 18))
      escreval("Idade <> 25: ", (idade > 25))
      escreval("Idade <> 25 e nome = Marcos: ", ((idade <> 25) E (nome = "Marcos")) )
      escreval("Idade dividida por 2 com resto = 0: ", ((idade % 2) = 0) )
Fimalgoritmo