Algoritmo "exercico1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/10/2022
Var
   j: INTEIRO
   n: INTEIRO
Inicio
      ESCREVAL("Digite um numero: ")
      LEIA(n)
      j <- 1
      ENQUANTO j < 11 FACA
               ESCREVAL(n, " * " ,j, " = ", n*j)
               j <- j+1
      FIMENQUANTO


Fimalgoritmo